#!/bin/bash
x=$(date +%Y%m%d%H%M%S)
cat /etc/passwd | awk -F : '{print $1}' > zad1.txt
cat /etc/group | awk -F : '{print $1}' > zad2.txt
sudo iptables -vL -t mangle  > zad3.txt
sudo netstat -ltnp --numeric-port > zad4.txt
ps -aux | less > zad5.txt
mkdir inwentaryzacja$x
mv *.txt inwentaryzacja$x
